# Generated by Django 4.2.6 on 2025-04-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adso_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedad',
            name='archivo',
            field=models.FileField(default=0, upload_to='evidencias/'),
            preserve_default=False,
        ),
    ]
