# Generated by Django 5.1.7 on 2025-04-19 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adso_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numero_documento',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='adso_app.rol'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, default='N/A', max_length=30),
        ),
    ]
